project:
  name: quickstart-amazon-aurora-postgresql
  shorten_stack_name: true
  owner: quickstart-eng@amazon.com
  package_lambda: false
  regions:
  - us-west-2
  - ap-south-1
  - eu-west-1
  - eu-north-1
  - us-east-1
  - ca-central-1
  - ap-northeast-1
  - ap-southeast-1
  - us-east-2
  - eu-west-2
  - eu-central-1
  - us-west-1
  - eu-west-3
  parameters:
    AvailabilityZones: $[taskcat_genaz_2]
    DBMasterUserPassword: "Ae6ii5fcckj4ddi0t!"
    EnableEventSubscription: "false"
    EnableBastion: "false"
    KeyPairName: $[taskcat_getkeypair]
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: $[taskcat_current_region]
    RemoteAccessCIDR: 10.0.0.0/16
tests:
  aurora-postgresql-14:
    parameters:
      DBEngineVersion: "14.5"
    template: ./templates/aurora_postgres-main.template.yaml
    regions:
      - us-west-2
  aurora-postgresql-13:
    parameters:
      DBEngineVersion: "13.8"
    template: ./templates/aurora_postgres-main.template.yaml
    regions:
      - ca-central-1
  aurora-postgresql-12:
    parameters:
      DBEngineVersion: "12.12"
    template: ./templates/aurora_postgres-main.template.yaml
    regions:
      - eu-west-2
