project:
  name: quickstart-amazon-aurora-postgresql
  owner: quickstart-eng@amazon.com
  package_lambda: false
  regions:
  - us-west-2
  - ap-south-1
  - eu-west-1
  - eu-north-1
  - us-east-1
  - ca-central-1
  - ap-northeast-1
  - ap-southeast-2
  - ap-southeast-1
  - ap-northeast-2
  - us-east-2
  - eu-west-2
  - eu-central-1
  - us-west-1
  - eu-west-3
tests:
  aurora-postgresql:
    parameters:
      AvailabilityZones: $[taskcat_genaz_2]
      DBEngineVersion: "10.6"
      DBMasterUserPassword: $[taskcat_genpass_8S]
      EnableEventSubscription: "false"
      EnableBastion: "false"
      KeyPairName: tonynv
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      RemoteAccessCIDR: 10.0.0.0/16
    template: ./templates/aurora_postgres-master.template.yaml
